version: '3'
services:
  registry-srv:
    image: registry:2
    hostname: registry-srv
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./docker-registry:/var/lib/registry
  registry-ui:
    image: joxit/docker-registry-ui:static
    ports:
      - "8080:80"
    restart: always
    environment: 
      - REGISTRY_URL=http://registry-srv:5000
      - DELETE_IMAGES=true
      - PULL_URL=http://10.249.182.84:5000