version: '3'
services:
  registry-srv:
    image: registry:2
    hostname: registry-srv
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /media/ices/327E75477E7504BF/docker/registry:/var/lib/registry
  registry-ui:
    image: joxit/docker-registry-ui:static
    ports:
      - "8080:80"
    restart: always
    environment: 
      - REGISTRY_URL=http://registry-srv:5000
      - DELETE_IMAGES=true