version: '3'
services:
  registry-srv:
    image: registry:2
    hostname: registry-srv
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /media/ices/327E75477E7504BF/docker/registry:/var/lib/registry
  registry-web:
    image: hyper/docker-registry-web
    ports: 
      - "8080:8080"
    restart: always
    depends_on: 
      - registry-srv
    environment: 
      - REGISTRY_URL=http://registry-srv:5000/v2
      - REGISTRY_NAME=registry-srv:5000